"""auto-stocks-rm-backpopulate

Revision ID: 43b3d06f3f28
Revises: a7d75cc848b7
Create Date: 2026-03-05 15:05:55.192342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b3d06f3f28'
down_revision: Union[str, Sequence[str], None] = 'a7d75cc848b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
