"""Orders-table-revision

Revision ID: 6573bdcd5335
Revises: e7ce923302b9
Create Date: 2026-03-06 09:47:43.538753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6573bdcd5335'
down_revision: Union[str, Sequence[str], None] = 'e7ce923302b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_status', sa.String(), nullable=False))
    op.add_column('order', sa.Column('payment_status', sa.String(), nullable=False))
    op.add_column('orderitem', sa.Column('price_locked', sa.Float(), nullable=False))
    op.drop_column('orderitem', 'price_at_purchase')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('price_at_purchase', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('orderitem', 'price_locked')
    op.drop_column('order', 'payment_status')
    op.drop_column('order', 'delivery_status')
    # ### end Alembic commands ###
