"""auto-issueticket-time

Revision ID: 735ec63b3170
Revises: aa6ad51101c4
Create Date: 2026-03-08 18:09:12.337438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735ec63b3170'
down_revision: Union[str, Sequence[str], None] = 'aa6ad51101c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issueticket', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('issueticket', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issueticket', 'updated_at')
    op.drop_column('issueticket', 'created_at')
    # ### end Alembic commands ###
