"""cart_item_col_created_at

Revision ID: caaed5ba0242
Revises: 1766004c90b3
Create Date: 2026-03-05 21:22:00.910816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caaed5ba0242'
down_revision: Union[str, Sequence[str], None] = '1766004c90b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitem', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartitem', 'created_at')
    # ### end Alembic commands ###
